# Generated by Django 4.1.4 on 2023-12-09 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumer', '0002_alter_customuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 21, 44, 7, 387397, tzinfo=datetime.timezone.utc)),
        ),
    ]
