# Generated by Django 4.1.4 on 2023-10-11 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumer', '0008_alter_customuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 11, 14, 7, 20, 810318, tzinfo=datetime.timezone.utc)),
        ),
    ]
