# Generated by Django 4.1.4 on 2023-10-12 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumer', '0013_alter_customuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 12, 9, 39, 24, 957775, tzinfo=datetime.timezone.utc)),
        ),
    ]
