# Generated by Django 4.1.4 on 2023-10-13 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumer', '0019_alter_customuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 13, 9, 44, 29, 962083, tzinfo=datetime.timezone.utc)),
        ),
    ]
