# Generated by Django 4.1.4 on 2023-10-13 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumer', '0021_alter_customuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 13, 16, 41, 37, 613199, tzinfo=datetime.timezone.utc)),
        ),
    ]
