# Generated by Django 4.1.4 on 2024-01-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typebien', models.CharField(max_length=255)),
                ('nombien', models.CharField(max_length=255)),
                ('nomchambre', models.CharField(max_length=255)),
                ('commune', models.CharField(max_length=255)),
                ('etoile', models.FloatField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacitelits', models.CharField(max_length=255)),
                ('apropos', models.TextField()),
                ('emplacement', models.CharField(max_length=255)),
                ('disponibilite', models.BooleanField(default=False)),
                ('reduction', models.CharField(max_length=255)),
                ('img1', models.ImageField(blank=True, upload_to='property_images/')),
                ('img2', models.ImageField(blank=True, upload_to='property_images/')),
                ('img3', models.ImageField(blank=True, upload_to='property_images/')),
                ('img4', models.ImageField(blank=True, upload_to='property_images/')),
                ('img5', models.ImageField(blank=True, upload_to='property_images/')),
                ('etablissement', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('nom', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typebien', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('nombrechambre', models.CharField(max_length=255)),
                ('img1', models.ImageField(blank=True, upload_to='property_images/')),
                ('img2', models.ImageField(blank=True, upload_to='property_images/')),
                ('img3', models.ImageField(blank=True, upload_to='property_images/')),
                ('img4', models.ImageField(blank=True, upload_to='property_images/')),
                ('img5', models.ImageField(blank=True, upload_to='property_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_chambre', models.IntegerField()),
                ('statut', models.CharField(default='En_cours', max_length=255)),
                ('date_arrive', models.DateField()),
                ('date_depart', models.DateField()),
                ('adulte', models.DecimalField(decimal_places=2, max_digits=10)),
                ('enfant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
    ]
