# Generated by Django 4.1.4 on 2023-10-17 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('numero', models.FloatField()),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_chambre', models.FloatField()),
                ('description', models.TextField()),
                ('statut', models.CharField(max_length=255)),
                ('etatpropriete', models.CharField(max_length=255)),
                ('etoile', models.FloatField()),
                ('logitude', models.DecimalField(decimal_places=2, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacitelits', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('region', models.CharField(max_length=255)),
                ('disponibilite', models.BooleanField(default=True)),
                ('numeromaintenance', models.CharField(max_length=255)),
                ('datedernieremaintenance', models.DateField()),
                ('reduction', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='property_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('date_arrive', models.DateField()),
                ('date_depart', models.DateField()),
                ('adulte', models.DecimalField(decimal_places=2, max_digits=10)),
                ('enfant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chambre')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reservation')),
            ],
        ),
    ]
