# Generated by Django 4.1.4 on 2023-10-10 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reservation'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chambre',
            name='bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bien'),
        ),
        migrations.AddField(
            model_name='chambre',
            name='equipements',
            field=models.ManyToManyField(blank=True, to='api.equipement'),
        ),
        migrations.AddField(
            model_name='chambre',
            name='images',
            field=models.ManyToManyField(to='api.image'),
        ),
        migrations.AddField(
            model_name='bien',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bien',
            name='services',
            field=models.ManyToManyField(to='api.service'),
        ),
    ]
