# Generated by Django 4.1.4 on 2024-03-11 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='auteur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='chambres',
            field=models.ManyToManyField(blank=True, related_name='etablissement_chambres', to='api.chambre'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reservation'),
        ),
        migrations.AddField(
            model_name='chambre',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chambre',
            name='equipements',
            field=models.ManyToManyField(blank=True, to='api.equipement'),
        ),
    ]
