# Generated by Django 4.1.4 on 2023-10-10 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chambre',
            name='capacite',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chambre'),
        ),
    ]
