# Generated by Django 4.1.4 on 2023-12-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chambre',
            name='statut',
        ),
        migrations.AlterField(
            model_name='chambre',
            name='disponibilite',
            field=models.BooleanField(default=False),
        ),
    ]
