# Generated by Django 4.1.4 on 2023-10-26 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_bien_images_alter_bien_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bien',
            name='chambre',
        ),
        migrations.AddField(
            model_name='chambre',
            name='bien',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.bien'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chambre',
            name='images',
            field=models.ManyToManyField(blank=True, to='api.image'),
        ),
    ]
