# Generated by Django 4.1.4 on 2023-10-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_chambre_capacite_alter_reservation_bien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='prix_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
