# Generated by Django 4.1.4 on 2023-12-09 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_chambre_statut_alter_chambre_disponibilite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='region',
        ),
    ]
