# Generated by Django 4.1.4 on 2023-10-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_reservation_prix_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='statut',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bien',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
