# Generated by Django 4.1.4 on 2023-10-28 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_bien_chambre_chambre_bien_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambre',
            name='type',
            field=models.CharField(default='Residence', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chambre',
            name='bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambres', to='api.bien'),
        ),
    ]
