# Generated by Django 4.1.4 on 2023-10-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_chambre_type_alter_chambre_bien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chambre',
            name='images',
        ),
        migrations.AddField(
            model_name='bien',
            name='img1',
            field=models.ImageField(blank=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='bien',
            name='img2',
            field=models.ImageField(blank=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='bien',
            name='img3',
            field=models.ImageField(blank=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='bien',
            name='img4',
            field=models.ImageField(blank=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='bien',
            name='img5',
            field=models.ImageField(blank=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='chambre',
            name='img1',
            field=models.ImageField(blank=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='chambre',
            name='img2',
            field=models.ImageField(blank=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='chambre',
            name='img3',
            field=models.ImageField(blank=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='chambre',
            name='img4',
            field=models.ImageField(blank=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='chambre',
            name='img5',
            field=models.ImageField(blank=True, upload_to='property_images/'),
        ),
    ]
