# Generated by Django 4.1.4 on 2023-10-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_bien_statut_alter_bien_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='numero',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
