# Generated by Django 4.1.4 on 2023-10-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_bien_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='numero',
            field=models.FloatField(),
        ),
    ]
