# Generated by Django 4.1.4 on 2023-10-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_reservation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='statut',
            field=models.CharField(default='En cours', max_length=255),
        ),
    ]
