# Generated by Django 4.1.4 on 2023-10-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_reservation_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambre',
            name='etoile',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
