# Generated by Django 4.1.4 on 2023-10-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_chambre_bien_bien_chambre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bien',
            old_name='capacite',
            new_name='nombre_chambre',
        ),
        migrations.AddField(
            model_name='bien',
            name='images',
            field=models.ManyToManyField(to='api.image'),
        ),
    ]
