# Generated by Django 4.1.4 on 2023-10-12 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_capacite_bien_nombre_chambre_bien_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bien',
            name='chambre',
        ),
        migrations.AddField(
            model_name='chambre',
            name='bien',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.bien'),
            preserve_default=False,
        ),
    ]
