# Generated by Django 4.1.4 on 2023-10-12 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_bien_chambre_chambre_bien'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='bien',
            new_name='chambre',
        ),
    ]
