# Generated by Django 4.1.4 on 2023-10-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_bien_reservation_chambre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chambre',
            name='bien',
        ),
        migrations.AddField(
            model_name='bien',
            name='chambre',
            field=models.ManyToManyField(to='api.chambre'),
        ),
    ]
