# Generated by Django 4.1.4 on 2023-10-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_bien_chambre_chambre_bien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chambre',
            name='bien',
        ),
        migrations.AddField(
            model_name='bien',
            name='chambre',
            field=models.ManyToManyField(blank=True, to='api.chambre'),
        ),
    ]
