# Generated by Django 4.1.4 on 2023-10-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_chambre_bien_bien_chambre'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='region',
            field=models.CharField(default='Sud Comoé', max_length=255),
            preserve_default=False,
        ),
    ]
