# Generated by Django 4.1.4 on 2023-10-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_bien_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambre',
            name='region',
            field=models.CharField(default='Sud Comoé', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='region',
            field=models.CharField(default='Sud Comoé', max_length=255),
            preserve_default=False,
        ),
    ]
