# Generated by Django 4.1.4 on 2023-10-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_chambre_region_reservation_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='latitude',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bien',
            name='logitude',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
