# Generated by Django 4.1.4 on 2023-10-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_bien_latitude_bien_logitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
